### ISSUE TITLE
Validation 'validating project version' failed!

### ISSUE THREAD

**Issue by ottuzzi** [git-commit-id/maven-git-commit-id-plugin#445] opened 2019-10-17 09:39 UTC
### Describe the bug
When I run the plugin in a multimodule project I get the error in the subject

### Steps to Reproduce
- mvn clean package

```[INFO] BUILD FAILURE                                                                                                                                                                            
[INFO] ------------------------------------------------------------------------                                                                                                                 
[INFO] Total time:  17.732 s                                                                                                                                                                    
[INFO] Finished at: 2019-10-17T11:32:55+02:00                                                                                                                                                   
[INFO] ------------------------------------------------------------------------                                                                                                                 
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:3.0.0:validateRevision (validate-the-git-infos) on project mdw-common: Validation 'validating project version' failed! Expected '0.0.1-SNAPSHOT' to match with '^.*(?<!-SNAPSHOT)$'! -> [Help 1]                                                                                                                         
[ERROR]                                                                                                                                                                                         
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.                                                                                                             
[ERROR] Re-run Maven using the -X switch to enable full debug logging.                                                                                                                          
[ERROR]                                                                                                                                                                                         
[ERROR] For more information about the errors and possible solutions, please read the following articles:                                                                                       
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException                                                                                                        
[ERROR]                                                                                                                                                                                         
[ERROR] After correcting the problems, you can resume the build with the command                                                                                                                
[ERROR]   mvn <goals> -rf :mdw-common                                                                                                                                                           
```

- Is there a (public) project where this issue can be reproduced? If so please provide a link.
No public project
- Include any stack-traces or any error messages

### Expected behavior
- It should work :)

### Additional context
For reproducibility please provide the following:

- the plugin version is being used (if not included in the configuration)
**3.0.1 (but also 3.0.0)**
- the Java-Version is being used (output of ``java -version`` and also include details about oracle-jdk VS open-jdk)
```
openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment Corretto-11.0.4.11.1 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.4.11.1 (build 11.0.4+11-LTS, mixed mode)
```
- the Maven-Version is being used (output of ``mvn --version``)
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: C:\Users\Piero\projects\apache-maven-3.6.0\bin\..
Java version: 11.0.4, vendor: Amazon.com Inc., runtime: C:\Program Files\Amazon Corretto\jdk11.0.4_10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
- on what Operating System you experience the bug (on Linux run ``lsb_release -a`` or ``cat /etc/*release*``)
- in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...)
**Conemu**
- how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)
`mvn clean package`

Feel free to add any other context or screenshots about the bug.

**Comment by TheSnoozer** [comment] 2019-10-17 12:59
Hello, thank you for reporting your problem here :-)
Based on your issue description the validation in question should look like this:
```xml
<plugin>
	<groupId>pl.project13.maven</groupId>
	<artifactId>git-commit-id-plugin</artifactId>
	<version>some-version</version>
	<executions>
		<!-- .... -->
		<execution>
			<id>validate-the-git-infos</id>
			<goals>
				<goal>validateRevision</goal>
			</goals>
			<phase>package</phase>
		</execution>
	</executions>
	<configuration>
		<!-- .... -->
		<validationProperties>
			<validationProperty>
				<name>validating project version</name>
				<value>${project.version}</value>
				<shouldMatchTo><![CDATA[^.*(?<!-SNAPSHOT)$]]></shouldMatchTo>
			</validationProperty>
		</validationProperties>
	</configuration>
</plugin>
```

The  `^.*(?<!-SNAPSHOT)$` is a [negative lookbehind regex](https://www.regextutorial.org/positive-and-negative-lookbehind-assertions.php) (or see [here](https://www.regular-expressions.info/lookaround.html)) witch essentially says `anything that is *not* ended by -SNAPSHOT`.
Certainly `0.0.1-SNAPSHOT` ends with `-SNAPSHOT` causing the regex not to match. In some sense it's meant as validation for deployment that you don't want to deploy SNAPSHOT-versions.

Perhaps a similar example ([source](https://www.regular-expressions.info/lookaround.html)):
The Regex `(?<!a)b` means matches a `b` that is not preceded by an `a` - using negative lookbehind.

See also:
https://regex101.com/r/tABLLV/1/

Hope this clarifies it, and I believe every version of this plugin should report this as failure (is there any where this does not happen?).

**Comment by TheSnoozer** [comment] 2019-11-03 17:00
I'm going ahead and close this as not a bug. Feel free to voice your opinion if you disagree. If you got any other issues or question don't hesitate to open a new issue.

**Closed by TheSnoozer** 2019-11-03 17:00 UTC
Labels: not-a-bug
